wip: create docker stages to run cypress and output test results

diff --git a/e2e/Dockerfile b/e2e/Dockerfile
--- a/e2e/Dockerfile
+++ b/e2e/Dockerfile
@@ -1,4 +1,4 @@
-FROM cypress/base:10
+FROM cypress/base:10 as tester
 WORKDIR /app
 
 # dependencies will be installed only if the package files change
@@ -14,3 +14,14 @@ RUN npm ci
 # running this command separately from "cypress run" will also cache its result
 # to avoid verifying again when running the tests
 RUN npx cypress verify
+
+FROM tester as test-run
+COPY ./cypress /app/cypress
+COPY ./cypress.json /app/
+RUN npx cypress run || echo "Tests failed! See test-results image."
+WORKDIR /app/cypress
+RUN tar -czvf test-results.tar.gz screenshots videos results
+# ENTRYPOINT [ "bash" ]
+
+FROM scratch as test-results
+COPY --from=test-run /app/cypress/test-results.tar.gz /
